# Generated by Django 4.0.6 on 2024-05-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default='2024-05-20'),
            preserve_default=False,
        ),
    ]
