# Generated by Django 4.0.6 on 2024-05-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_baja',
            field=models.DateField(null=True),
        ),
    ]
