# Generated by Django 5.0.6 on 2024-06-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_fecha_baja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
