# Generated by Django 5.0.6 on 2024-06-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_producto_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
