# Generated by Django 5.0.6 on 2024-06-12 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_alta',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
