# Generated by Django 5.0.6 on 2024-06-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_categoria_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_baja',
        ),
    ]
